export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export const FEATURED_FETCH_REQUEST = 'FEATURED_FETCH_REQUEST';
export const FEATURED_FETCH_REQUEST_SUCCESS = 'FEATURED_FETCH_REQUEST_SUCCESS';
export const FEATURED_FETCH_REQUEST_FAILURE = 'FEATURED_FETCH_REQUEST_FAILURE';
export const FEATURED_CLEAN_REQUEST = 'FEATURED_CLEAN_REQUEST';

// Homepage CURRENT_TOP_HITS
export const CURRENT_TOP_HITS_FETCH_REQUEST = 'CURRENT_TOP_HITS_FETCH_REQUEST';
export const CURRENT_TOP_HITS_FETCH_REQUEST_SUCCESS = 'CURRENT_TOP_HITS_FETCH_REQUEST_SUCCESS';
export const CURRENT_TOP_HITS_FETCH_REQUEST_FAILURE = 'CURRENT_TOP_HITS_FETCH_REQUEST_FAILURE';
export const CURRENT_TOP_HITS_CLEAN_REQUEST = 'CURRENT_TOP_HITS_CLEAN_REQUEST';

// current Playing songs / playlist
export const CURRENT_PLAY_SONG = 'CURRENT_PLAY_SONG';
export const CURRENT_PLAYER_IS_PLAYING = 'CURRENT_PLAYER_IS_PLAYING';
export const CURRENT_PLAYLIST = 'CURRENT_PLAYLIST';
export const CURRENT_PLAY_SONG_ID = 'CURRENT_PLAY_SONG_ID';
export const CURRENT_PLAY_IS_BULK_PLAYING = 'CURRENT_PLAY_IS_BULK_PLAYING';
export const CLEAR_CURRENT_PLAY_SONGS ="CLEAR_CURRENT_PLAY_SONGS"



// Homepage FRESH_OUT_OF_MARKET
export const FRESH_FETCH_REQUEST = 'FRESH_FETCH_REQUEST';
export const FRESH_FETCH_REQUEST_SUCCESS = 'FRESH_FETCH_REQUEST_SUCCESS';
export const FRESH_FETCH_REQUEST_FAILURE = 'FRESH_FETCH_REQUEST_FAILURE';
export const FRESH_CLEAN_REQUEST = 'FRESH_CLEAN_REQUEST';

// Homepage Popular on Songs Nepal
export const POPULAR_SONGS_FETCH_REQUEST = 'POPULAR_SONGS_FETCH_REQUEST';
export const POPULAR_SONGS_FETCH_REQUEST_SUCCESS = 'POPULAR_SONGS_FETCH_REQUEST_SUCCESS';
export const POPULAR_SONGS_FETCH_REQUEST_FAILURE = 'POPULAR_SONGS_FETCH_REQUEST_FAILURE';
export const POPULAR_SONGS_CLEAN_REQUEST = 'POPULAR_SONGS_CLEAN_REQUEST';

// Homepage Top Songs Nepal
export const TOP_SONGS_FETCH_REQUEST = 'TOP_SONGS_FETCH_REQUEST';
export const TOP_SONGS_FETCH_REQUEST_SUCCESS = 'TOP_SONGS_FETCH_REQUEST_SUCCESS';
export const TOP_SONGS_FETCH_REQUEST_FAILURE = 'TOP_SONGS_FETCH_REQUEST_FAILURE';
export const TOP_SONGS_FETCH_MORE_REQUEST = 'TOP_SONGS_FETCH_MORE_REQUEST';
export const TOP_SONGS_FETCH_MORE_REQUEST_SUCCESS = 'TOP_SONGS_FETCH_MORE_REQUEST_SUCCESS';
export const TOP_SONGS_FETCH_MORE_REQUEST_FAILURE = 'TOP_SONGS_FETCH_MORE_REQUEST_FAILURE';
export const TOP_SONGS_FETCH_META = 'TOP_SONGS_FETCH_META';
export const TOP_SONGS_CLEAN_REQUEST = 'TOP_SONGS_CLEAN_REQUEST';

// Homepage Recently played
export const RECENTLY_PLAYED_FETCH_REQUEST = 'RECENTLY_PLAYED_FETCH_REQUEST';
export const RECENTLY_PLAYED_FETCH_REQUEST_SUCCESS = 'RECENTLY_PLAYED_FETCH_REQUEST_SUCCESS';
export const RECENTLY_PLAYED_FETCH_REQUEST_FAILURE = 'RECENTLY_PLAYED_FETCH_REQUEST_FAILURE';
export const RECENTLY_PLAYED_CLEAN_REQUEST = 'RECENTLY_PLAYED_CLEAN_REQUEST';

// Recently played All
export const RECENTLY_PLAYED_ALL_FETCH_REQUEST = 'RECENTLY_PLAYED_ALL_FETCH_REQUEST';
export const RECENTLY_PLAYED_ALL_FETCH_MORE_REQUEST = 'RECENTLY_PLAYED_ALL_FETCH_MORE_REQUEST';
export const RECENTLY_PLAYED_ALL_FETCH_REQUEST_SUCCESS = 'RECENTLY_PLAYED_ALL_FETCH_REQUEST_SUCCESS';
export const RECENTLY_PLAYED_ALL_FETCH_MORE_REQUEST_SUCCESS = 'RECENTLY_PLAYED_ALL_FETCH_MORE_REQUEST_SUCCESS';
export const RECENTLY_PLAYED_ALL_FETCH_REQUEST_FAILURE = 'RECENTLY_PLAYED_ALL_FETCH_REQUEST_FAILURE';
export const RECENTLY_PLAYED_ALL_FETCH_MORE_REQUEST_FAILURE = 'RECENTLY_PLAYED_ALL_FETCH_MORE_REQUEST_FAILURE';
export const RECENTLY_PLAYED_ALL_CLEAN_REQUEST = 'RECENTLY_PLAYED_ALL_CLEAN_REQUEST';
export const RECENTLY_PLAYED_ALL_FETCH_META_INFO = 'RECENTLY_PLAYED_ALL_FETCH_META_INFO';

// Homepage Recommended Artists
export const RECOMMENDED_ARTISTS_FETCH_REQUEST = 'RECOMMENDED_ARTISTS_FETCH_REQUEST';
export const RECOMMENDED_ARTISTS_FETCH_REQUEST_SUCCESS = 'RECOMMENDED_ARTISTS_FETCH_REQUEST_SUCCESS';
export const RECOMMENDED_ARTISTS_FETCH_REQUEST_FAILURE = 'RECOMMENDED_ARTISTS_FETCH_REQUEST_FAILURE';
export const RECOMMENDED_ARTISTS_CLEAN_REQUEST = 'RECOMMENDED_ARTISTS_CLEAN_REQUEST';

// Homepage Recommended Artists
export const RECOMMENDED_ALBUMS_FETCH_REQUEST = 'RECOMMENDED_ALBUMS_FETCH_REQUEST';
export const RECOMMENDED_ALBUMS_FETCH_REQUEST_SUCCESS = 'RECOMMENDED_ALBUMS_FETCH_REQUEST_SUCCESS';
export const RECOMMENDED_ALBUMS_FETCH_REQUEST_FAILURE = 'RECOMMENDED_ALBUMS_FETCH_REQUEST_FAILURE';
export const RECOMMENDED_ALBUMS_CLEAN_REQUEST = 'RECOMMENDED_ALBUMS_CLEAN_REQUEST';

// Homepage Playlists Suggestion
export const PLAYLISTS_SUGGESTION_FETCH_REQUEST = 'PLAYLISTS_SUGGESTION_FETCH_REQUEST';
export const PLAYLISTS_SUGGESTION_FETCH_REQUEST_SUCCESS = 'PLAYLISTS_SUGGESTION_FETCH_REQUEST_SUCCESS';
export const PLAYLISTS_SUGGESTION_FETCH_REQUEST_FAILURE = 'PLAYLISTS_SUGGESTION_FETCH_REQUEST_FAILURE';
export const PLAYLISTS_SUGGESTION_CLEAN_REQUEST = 'PLAYLISTS_SUGGESTION_CLEAN_REQUEST';

// Browse Genres
export const GENRES_FETCH_REQUEST = 'GENRES_FETCH_REQUEST';
export const GENRES_FETCH_REQUEST_SUCCESS = 'GENRES_FETCH_REQUEST_SUCCESS';
export const GENRES_FETCH_REQUEST_FAILURE = 'GENRES_FETCH_REQUEST_FAILURE';
export const GENRES_CLEAN_REQUEST = 'GENRES_CLEAN_REQUEST';

// Individual Fetch
export const INDIVIDUAL_FETCH_REQUEST = 'INDIVIDUAL_FETCH_REQUEST';
export const INDIVIDUAL_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_CLEAN_REQUEST = 'INDIVIDUAL_CLEAN_REQUEST';

// Individual Genre Song Fetch
export const INDIVIDUAL_GENRE_SONGS_FETCH_REQUEST = 'INDIVIDUAL_GENRE_SONGS_FETCH_REQUEST';
export const INDIVIDUAL_GENRE_SONGS_FETCH_MORE_REQUEST = 'INDIVIDUAL_GENRE_SONGS_FETCH_MORE_REQUEST';
export const INDIVIDUAL_GENRE_SONGS_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_SONGS_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_SONGS_FETCH_MORE_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_SONGS_FETCH_MORE_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_SONGS_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_SONGS_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_SONGS_FETCH_MORE_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_SONGS_FETCH_MORE_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_SONGS_CLEAN_REQUEST = 'INDIVIDUAL_GENRE_SONGS_CLEAN_REQUEST';
export const INDIVIDUAL_GENRE_SONGS_FETCH_META_INFO = 'INDIVIDUAL_GENRE_SONGS_FETCH_META_INFO';

// Individual Genre Album Fetch
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_REQUEST = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_REQUEST';
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_MORE_REQUEST = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_MORE_REQUEST';
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_MORE_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_MORE_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_MORE_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_MORE_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_ALBUMS_FETCH_META_INFO = 'INDIVIDUAL_GENRE_ALBUMS_FETCH_META_INFO';
export const INDIVIDUAL_GENRE_ALBUMS_CLEAN_REQUEST = 'INDIVIDUAL_GENRE_ALBUMS_CLEAN_REQUEST';

// Individual Genre Artists Fetch
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_REQUEST = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_REQUEST';
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_MORE_REQUEST = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_MORE_REQUEST';
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_MORE_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_MORE_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_MORE_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_MORE_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_ARTISTS_FETCH_META_INFO = 'INDIVIDUAL_GENRE_ARTISTS_FETCH_META_INFO';
export const INDIVIDUAL_GENRE_ARTISTS_CLEAN_REQUEST = 'INDIVIDUAL_GENRE_ARTISTS_CLEAN_REQUEST';

// Individual Genre Playlists Fetch
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_REQUEST = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_REQUEST';
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_MORE_REQUEST = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_MORE_REQUEST';
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_MORE_REQUEST_SUCCESS = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_MORE_REQUEST_SUCCESS';
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_MORE_REQUEST_FAILURE = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_MORE_REQUEST_FAILURE';
export const INDIVIDUAL_GENRE_PLAYLISTS_FETCH_META = 'INDIVIDUAL_GENRE_PLAYLISTS_FETCH_META';
export const INDIVIDUAL_GENRE_PLAYLISTS_CLEAN_REQUEST = 'INDIVIDUAL_GENRE_PLAYLISTS_CLEAN_REQUEST';

// Browse Moods
export const MOODS_FETCH_REQUEST = 'MOODS_FETCH_REQUEST';
export const MOODS_FETCH_REQUEST_SUCCESS = 'MOODS_FETCH_REQUEST_SUCCESS';
export const MOODS_FETCH_REQUEST_FAILURE = 'MOODS_FETCH_REQUEST_FAILURE';
export const MOODS_CLEAN_REQUEST = 'MOODS_CLEAN_REQUEST';

// Browse Moods
export const SEARCH_FETCH_REQUEST = 'SEARCH_FETCH_REQUEST';
export const SEARCH_FETCH_REQUEST_SUCCESS = 'SEARCH_FETCH_REQUEST_SUCCESS';
export const SEARCH_FETCH_REQUEST_FAILURE = 'SEARCH_FETCH_REQUEST_FAILURE';
export const SEARCH_CLEAN_REQUEST = 'SEARCH_CLEAN_REQUEST';
export const SET_SEARCH_KEY ="SET_SEARCH_KEY";
export const SEARCH_LOAD_MORE_REQUEST = 'SEARCH_LOAD_MORE_REQUEST'
export const SEARCH_LOAD_MORE_SUCCESS = 'SEARCH_LOAD_MORE_SUCCESS'
//Moods Songs
export const INDIVIDUAL_MOOD_SONGS_FETCH_REQUEST = 'INDIVIDUAL_MOOD_SONGS_FETCH_REQUEST';
export const INDIVIDUAL_MOOD_SONGS_FETCH_MORE_REQUEST = 'INDIVIDUAL_MOOD_SONGS_FETCH_MORE_REQUEST';
export const INDIVIDUAL_MOOD_SONGS_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_MOOD_SONGS_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_MOOD_SONGS_FETCH_MORE_REQUEST_SUCCESS = 'INDIVIDUAL_MOOD_SONGS_FETCH_MORE_REQUEST_SUCCESS';
export const INDIVIDUAL_MOOD_SONGS_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_MOOD_SONGS_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_MOOD_SONGS_FETCH_MORE_REQUEST_FAILURE = 'INDIVIDUAL_MOOD_SONGS_FETCH_MORE_REQUEST_FAILURE';
export const INDIVIDUAL_MOOD_SONGS_CLEAN_REQUEST = 'INDIVIDUAL_MOOD_SONGS_CLEAN_REQUEST';
export const INDIVIDUAL_MOOD_SONGS_FETCH_META_INFO = 'INDIVIDUAL_MOOD_SONGS_FETCH_META_INFO';



// new releases latest songs
export const LATEST_SONGS_FETCH_REQUEST = 'LATEST_SONGS_FETCH_REQUEST';
export const LATEST_SONGS_FETCH_REQUEST_SUCCESS = 'LATEST_SONGS_FETCH_REQUEST_SUCCESS';
export const LATEST_SONGS_FETCH_REQUEST_FAILURE = 'LATEST_SONGS_FETCH_REQUEST_FAILURE';
export const LATEST_SONGS_CLEAN_REQUEST = 'LATEST_SONGS_CLEAN_REQUEST';

// new releases latest songs all
export const LATEST_SONGS_ALL_FETCH_REQUEST = 'LATEST_SONGS_ALL_FETCH_REQUEST';
export const LATEST_SONGS_ALL_FETCH_REQUEST_SUCCESS = 'LATEST_SONGS_ALL_FETCH_REQUEST_SUCCESS';
export const LATEST_SONGS_ALL_FETCH_REQUEST_FAILURE = 'LATEST_SONGS_ALL_FETCH_REQUEST_FAILURE';
export const LATEST_SONGS_ALL_FETCH_MORE_REQUEST = 'LATEST_SONGS_ALL_FETCH_MORE_REQUEST';
export const LATEST_SONGS_ALL_FETCH_MORE_REQUEST_SUCCESS = 'LATEST_SONGS_ALL_FETCH_MORE_REQUEST_SUCCESS';
export const LATEST_SONGS_ALL_FETCH_MORE_REQUEST_FAILURE = 'LATEST_SONGS_ALL_FETCH_MORE_REQUEST_FAILURE';
export const LATEST_SONGS_ALL_FETCH_META = 'LATEST_SONGS_ALL_FETCH_META';
export const LATEST_SONGS_ALL_CLEAN_REQUEST = 'LATEST_SONGS_ALL_CLEAN_REQUEST';

// new releases latest albums
export const LATEST_ALBUMS_FETCH_REQUEST = 'LATEST_ALBUMS_FETCH_REQUEST';
export const LATEST_ALBUMS_FETCH_REQUEST_SUCCESS = 'LATEST_ALBUMS_FETCH_REQUEST_SUCCESS';
export const LATEST_ALBUMS_FETCH_REQUEST_FAILURE = 'LATEST_ALBUMS_FETCH_REQUEST_FAILURE';
export const LATEST_ALBUMS_CLEAN_REQUEST = 'LATEST_ALBUMS_CLEAN_REQUEST';

// new releases latest albums all
export const LATEST_ALBUMS_ALL_FETCH_REQUEST = 'LATEST_ALBUMS_ALL_FETCH_REQUEST';
export const LATEST_ALBUMS_ALL_FETCH_REQUEST_SUCCESS = 'LATEST_ALBUMS_ALL_FETCH_REQUEST_SUCCESS';
export const LATEST_ALBUMS_ALL_FETCH_REQUEST_FAILURE = 'LATEST_ALBUMS_ALL_FETCH_REQUEST_FAILURE';
export const LATEST_ALBUMS_ALL_FETCH_MORE_REQUEST = 'LATEST_ALBUMS_ALL_FETCH_MORE_REQUEST';
export const LATEST_ALBUMS_ALL_FETCH_MORE_REQUEST_SUCCESS = 'LATEST_ALBUMS_ALL_FETCH_MORE_REQUEST_SUCCESS';
export const LATEST_ALBUMS_ALL_FETCH_MORE_REQUEST_FAILURE = 'LATEST_ALBUMS_ALL_FETCH_MORE_REQUEST_FAILURE';
export const LATEST_ALBUMS_ALL_FETCH_META = 'LATEST_ALBUMS_ALL_FETCH_META';
export const LATEST_ALBUMS_ALL_CLEAN_REQUEST = 'LATEST_ALBUMS_ALL_CLEAN_REQUEST';

// new releases latest artists
export const LATEST_ARTISTS_FETCH_REQUEST = 'LATEST_ARTISTS_FETCH_REQUEST';
export const LATEST_ARTISTS_FETCH_REQUEST_SUCCESS = 'LATEST_ARTISTS_FETCH_REQUEST_SUCCESS';
export const LATEST_ARTISTS_FETCH_REQUEST_FAILURE = 'LATEST_ARTISTS_FETCH_REQUEST_FAILURE';
export const LATEST_ARTISTS_CLEAN_REQUEST = 'LATEST_ARTISTS_CLEAN_REQUEST';

// new releases latest artists all
export const LATEST_ARTISTS_ALL_FETCH_REQUEST = 'LATEST_ARTISTS_ALL_FETCH_REQUEST';
export const LATEST_ARTISTS_ALL_FETCH_REQUEST_SUCCESS = 'LATEST_ARTISTS_ALL_FETCH_REQUEST_SUCCESS';
export const LATEST_ARTISTS_ALL_FETCH_REQUEST_FAILURE = 'LATEST_ARTISTS_ALL_FETCH_REQUEST_FAILURE';
export const LATEST_ARTISTS_ALL_FETCH_MORE_REQUEST = 'LATEST_ARTISTS_ALL_FETCH_MORE_REQUEST';
export const LATEST_ARTISTS_ALL_FETCH_MORE_REQUEST_SUCCESS = 'LATEST_ARTISTS_ALL_FETCH_MORE_REQUEST_SUCCESS';
export const LATEST_ARTISTS_ALL_FETCH_MORE_REQUEST_FAILURE = 'LATEST_ARTISTS_ALL_FETCH_MORE_REQUEST_FAILURE';
export const LATEST_ARTISTS_ALL_FETCH_META = 'LATEST_ARTISTS_ALL_FETCH_META';
export const LATEST_ARTISTS_ALL_CLEAN_REQUEST = 'LATEST_ARTISTS_CLEAN_REQUEST';

// favorite artists 
export const FAVORITE_ARTISTS_FETCH_REQUEST = 'FAVORITE_ARTISTS_FETCH_REQUEST';
export const FAVOURITE_ARTIST_FOLLOW_REQUEST = 'FAVOURITE_ARTIST_FOLLOW_REQUEST';
export const FAVOURITE_ARTIST_FOLLOW_SUCCESS = 'FAVOURITE_ARTIST_FOLLOW_SUCCESS';
export const FAVORITE_ARTISTS_FETCH_REQUEST_SUCCESS = 'FAVORITE_ARTISTS_FETCH_REQUEST_SUCCESS';
export const FAVORITE_ARTISTS_FETCH_REQUEST_FAILURE = 'FAVORITE_ARTISTS_FETCH_REQUEST_FAILURE';
export const FAVORITE_ARTISTS_CLEAN_REQUEST = 'FAVORITE_ARTISTS_CLEAN_REQUEST';
export const FAVORITE_ARTISTS_FETCH_MORE_REQUEST = 'FAVORITE_ARTISTS_FETCH_MORE_REQUEST';
export const FAVORITE_ARTISTS_FETCH_MORE_REQUEST_SUCCESS = 'FAVORITE_ARTISTS_FETCH_MORE_REQUEST_SUCCESS';
export const FAVORITE_ARTISTS_FETCH_MORE_REQUEST_FAILURE = 'FAVORITE_ARTISTS_FETCH_MORE_REQUEST_FAILURE';
export const FAVORITE_ARTISTS_FETCH_META = 'FAVORITE_ARTISTS_FETCH_META';


// favorite albums 
export const FAVORITE_ALBUMS_FETCH_REQUEST = 'FAVORITE_ALBUMS_FETCH_REQUEST';
export const FAVORITE_ALBUMS_FETCH_ID_REQUEST = 'FAVORITE_ALBUMS_FETCH_ID_REQUEST';
export const FAVORITE_ALBUMS_FETCH_REQUEST_SUCCESS = 'FAVORITE_ALBUMS_FETCH_REQUEST_SUCCESS';
export const FAVORITE_ALBUMS_SUCCESS ='FAVORITE_ALBUMS_SUCCESS';
export const FAVORITE_ALBUMS_FETCH_REQUEST_FAILURE = 'FAVORITE_ALBUMS_FETCH_REQUEST_FAILURE';
export const FAVORITE_ALBUMS_CLEAN_REQUEST = 'FAVORITE_ALBUMS_CLEAN_REQUEST';
export const FAVORITE_ALBUMS_FETCH_MORE_REQUEST = 'FAVORITE_ALBUMS_FETCH_MORE_REQUEST';
export const FAVORITE_ALBUMS_FETCH_MORE_REQUEST_SUCCESS = 'FAVORITE_ALBUMS_FETCH_MORE_REQUEST_SUCCESS';
export const FAVORITE_ALBUMS_FETCH_MORE_REQUEST_FAILURE = 'FAVORITE_ALBUMS_FETCH_MORE_REQUEST_FAILURE';
export const FAVORITE_ALBUMS_FETCH_META = 'FAVORITE_ALBUMS_FETCH_META';

// favorite songs 
export const FAVORITE_SONGS_FETCH_REQUEST = 'FAVORITE_SONGS_FETCH_REQUEST';

export const FAVORITE_SONGS_FETCH_REQUEST_SUCCESS = 'FAVORITE_SONGS_FETCH_REQUEST_SUCCESS';

export const FAVORITE_SONGS_FETCH_DETAIL_SUCCESS = 'FAVORITE_SONGS_FETCH_DETAIL_SUCCESS';
export const FAVORITE_SONGS_FETCH_REQUEST_FAILURE = 'FAVORITE_SONGS_FETCH_REQUEST_FAILURE';

export const FAVORITE_SONGS_CLEAN_REQUEST = 'FAVORITE_SONGS_CLEAN_REQUEST';

 //favorite songs all
 export const FAVORITE_SONGS_ALL_FETCH_REQUEST='FAVORITE_SONGS_ALL_FETCH_REQUEST';
 export const FAVORITE_SONGS_ALL_FETCH_REQUEST_SUCCESS='FAVORITE_SONGS_ALL_FETCH_REQUEST_SUCCESS';
 export const  FAVORITE_SONGS_ALL_FETCH_REQUEST_FAILURE='FAVORITE_SONGS_ALL_FETCH_REQUEST_FAILURE';
 export const  FAVORITE_SONGS_ALL_CLEAN_REQUEST='FAVORITE_SONGS_ALL_CLEAN_REQUEST';
 export const   FAVORITE_SONGS_ALL_FETCH_DETAIL_SUCCESS='FAVORITE_SONGS_ALL_FETCH_DETAIL_SUCCESS';
 export const   FAVORITE_SONGS_ALL_FETCH_MORE_REQUEST='FAVORITE_SONGS_ALL_FETCH_MORE_REQUEST';
 export const  FAVORITE_SONGS_ALL_FETCH_MORE_REQUEST_SUCCESS='FAVORITE_SONGS_ALL_FETCH_MORE_REQUEST_SUCCESS';
 export const  FAVORITE_SONGS_ALL_FETCH_MORE_REQUEST_FAILURE='FAVORITE_SONGS_ALL_FETCH_MORE_REQUEST_FAILURE';
 export const  FAVORITE_SONGS_ALL_FETCH_META_INFO='FAVORITE_SONGS_ALL_FETCH_META_INFO';
// explore songs / songs by genre
export const EXPLORE_SONGS_FETCH_REQUEST = 'EXPLORE_SONGS_FETCH_REQUEST';
export const EXPLORE_SONGS_FETCH_REQUEST_SUCCESS = 'EXPLORE_SONGS_FETCH_REQUEST_SUCCESS';
export const EXPLORE_SONGS_FETCH_REQUEST_FAILURE = 'EXPLORE_SONGS_FETCH_REQUEST_FAILURE';
export const EXPLORE_SONGS_CLEAN_REQUEST = 'EXPLORE_SONGS_CLEAN_REQUEST';
export const EXPLORE_SONGS_FETCH_MORE_REQUEST = 'EXPLORE_SONGS_FETCH_MORE_REQUEST';
export const EXPLORE_SONGS_FETCH_MORE_REQUEST_SUCCESS = 'EXPLORE_SONGS_FETCH_MORE_REQUEST_SUCCESS';
export const EXPLORE_SONGS_FETCH_MORE_REQUEST_FAILURE = 'EXPLORE_SONGS_FETCH_MORE_REQUEST_FAILURE';
export const EXPLORE_SONGS_FETCH_META = 'EXPLORE_SONGS_FETCH_META';


// explore albums / albums by genre
export const EXPLORE_ALBUMS_FETCH_REQUEST = 'EXPLORE_ALBUMS_FETCH_REQUEST';
export const EXPLORE_ALBUMS_FETCH_REQUEST_SUCCESS = 'EXPLORE_ALBUMS_FETCH_REQUEST_SUCCESS';
export const EXPLORE_ALBUMS_FETCH_REQUEST_FAILURE = 'EXPLORE_ALBUMS_FETCH_REQUEST_FAILURE';
export const EXPLORE_ALBUMS_FETCH_MORE_REQUEST = 'EXPLORE_ALBUMS_FETCH_MORE_REQUEST';
export const EXPLORE_ALBUMS_FETCH_MORE_REQUEST_SUCCESS = 'EXPLORE_ALBUMS_FETCH_MORE_REQUEST_SUCCESS';
export const EXPLORE_ALBUMS_FETCH_MORE_REQUEST_FAILURE = 'EXPLORE_ALBUMS_FETCH_MORE_REQUEST_FAILURE';
export const EXPLORE_ALBUMS_FETCH_META = 'EXPLORE_ALBUMS_FETCH_META';
export const EXPLORE_ALBUMS_CLEAN_REQUEST = 'EXPLORE_ALBUMS_CLEAN_REQUEST';

// explore artists / artists by genre
export const EXPLORE_ARTISTS_FETCH_REQUEST = 'EXPLORE_ARTISTS_FETCH_REQUEST';
export const EXPLORE_ARTISTS_FETCH_REQUEST_SUCCESS = 'EXPLORE_ARTISTS_FETCH_REQUEST_SUCCESS';
export const EXPLORE_ARTISTS_FETCH_REQUEST_FAILURE = 'EXPLORE_ARTISTS_FETCH_REQUEST_FAILURE';
export const EXPLORE_ARTISTS_CLEAN_REQUEST = 'EXPLORE_ARTISTS_CLEAN_REQUEST';
export const EXPLORE_ARTISTS_FETCH_MORE_REQUEST = 'EXPLORE_ARTISTS_FETCH_MORE_REQUEST';
export const EXPLORE_ARTISTS_FETCH_MORE_REQUEST_SUCCESS = 'EXPLORE_ARTISTS_FETCH_MORE_REQUEST_SUCCESS';
export const EXPLORE_ARTISTS_FETCH_MORE_REQUEST_FAILURE = 'EXPLORE_ARTISTS_FETCH_MORE_REQUEST_FAILURE';
export const EXPLORE_ARTISTS_FETCH_META = 'EXPLORE_ARTISTS_FETCH_META';


// explore playlists / playlists by genre
export const EXPLORE_PLAYLISTS_FETCH_REQUEST = 'EXPLORE_PLAYLISTS_FETCH_REQUEST';
export const EXPLORE_PLAYLISTS_FETCH_REQUEST_SUCCESS = 'EXPLORE_PLAYLISTS_FETCH_REQUEST_SUCCESS';
export const EXPLORE_PLAYLISTS_FETCH_REQUEST_FAILURE = 'EXPLORE_PLAYLISTS_FETCH_REQUEST_FAILURE';
export const EXPLORE_PLAYLISTS_FETCH_MORE_REQUEST = 'EXPLORE_PLAYLISTS_FETCH_MORE_REQUEST';
export const EXPLORE_PLAYLISTS_FETCH_MORE_REQUEST_SUCCESS = 'EXPLORE_PLAYLISTS_FETCH_MORE_REQUEST_SUCCESS';
export const EXPLORE_PLAYLISTS_FETCH_MORE_REQUEST_FAILURE = 'EXPLORE_PLAYLISTS_FETCH_MORE_REQUEST_FAILURE';
export const EXPLORE_PLAYLISTS_FETCH_META = 'EXPLORE_PLAYLISTS_FETCH_META';
export const EXPLORE_PLAYLISTS_CLEAN_REQUEST = 'EXPLORE_PLAYLISTS_CLEAN_REQUEST';

//user recent playlists 
export const USER_RECENT_PLAYLISTS_FETCH_REQUEST = 'USER_RECENT_PLAYLISTS_FETCH_REQUEST';
export const USER_RECENT_PLAYLISTS_FETCH_REQUEST_SUCCESS = 'USER_RECENT_PLAYLISTS_FETCH_REQUEST_SUCCESS';
export const USER_RECENT_PLAYLISTS_FETCH_REQUEST_FAILURE = 'USER_RECENT_PLAYLISTS_FETCH_REQUEST_FAILURE';
export const USER_RECENT_PLAYLISTS_CLEAN_REQUEST = 'USER_RECENT_PLAYLISTS_CLEAN_REQUEST';

//user Profile
export const USER_PROFILE_FETCH_REQUEST = 'USER_PROFILE_FETCH_REQUEST';
export const USER_PROFILE_FETCH_REQUEST_SUCCESS = 'USER_PROFILE_FETCH_REQUEST_SUCCESS';
export const USER_PROFILE_FETCH_REQUEST_FAILURE = 'USER_PROFILE_FETCH_REQUEST_FAILURE';
export const USER_PROFILE_CLEAN_REQUEST = 'USER_PROFILE_CLEAN_REQUEST';

//user Profile Update
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_REQUEST_SUCCESS = 'USER_PROFILE_UPDATE_REQUEST_SUCCESS';
export const USER_PROFILE_UPDATE_REQUEST_FAILURE = 'USER_PROFILE_UPDATE_REQUEST_FAILURE';
export const USER_PROFILE_UPDATE_CLEAN_REQUEST = 'USER_PROFILE_UPDATE_CLEAN_REQUEST';

//user Profile
export const USER_PASSWORD_UPDATE_REQUEST = 'USER_PASSWORD_UPDATE_REQUEST';
export const USER_PASSWORD_UPDATE_REQUEST_SUCCESS = 'USER_PASSWORD_UPDATE_REQUEST_SUCCESS';
export const USER_PASSWORD_UPDATE_REQUEST_FAILURE = 'USER_PROFILE_UPDATE_REQUEST_FAILURE';
export const USER_PASSWORD_UPDATE_CLEAN_REQUEST = 'USER_PASSWORD_UPDATE_CLEAN_REQUEST';

//user Profile Data
export const USER_DATA_FETCH_REQUEST = 'USER_DATA_FETCH_REQUEST';
export const USER_DATA_FETCH_REQUEST_SUCCESS = 'USER_DATA_FETCH_REQUEST_SUCCESS';
export const USER_DATA_FETCH_REQUEST_FAILURE = 'USER_DATA_FETCH_REQUEST_FAILURE';
export const USER_DATA_CLEAN_REQUEST = 'USER_DATA_CLEAN_REQUEST';

//user all playlists 
export const USER_ALL_PLAYLISTS_FETCH_REQUEST = 'USER_ALL_PLAYLISTS_FETCH_REQUEST';
export const USER_ALL_PLAYLISTS_FETCH_REQUEST_SUCCESS = 'USER_ALL_PLAYLISTS_FETCH_REQUEST_SUCCESS';
export const USER_ALL_PLAYLISTS_FETCH_REQUEST_FAILURE = 'USER_ALL_PLAYLISTS_FETCH_REQUEST_FAILURE';
export const USER_ALL_PLAYLISTS_CLEAN_REQUEST = 'USER_ALL_PLAYLISTS_CLEAN_REQUEST';
export const UPDATE_USER_PLAYLIST_REQUEST = 'UPDATE_USER_PLAYLIST_REQUEST';
export const UPDATE_USER_PLAYLIST_SUCCESS = 'UPDATE_USER_PLAYLIST_SUCCESS';
export const UPDATE_USER_PLAYLIST_FAIL = 'UPDATE_USER_PLAYLIST_FAIL';
export const REMOVE_SONG_FROM_PLAYLIST_SUCCESS = 'REMOVE_SONG_FROM_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_REQUEST = "DELETE_PLAYLIST_REQUEST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL";

// add to playlist
export const ADD_TO_PLAYLIST_REQUEST = 'ADD_TO_PLAYLIST_REQUEST';
export const ADD_TO_PLAYLIST_REQUEST_SUCCESS = 'ADD_TO_PLAYLIST_REQUEST_SUCCESS';
export const ADD_TO_PLAYLIST_REQUEST_FAILURE = 'ADD_TO_PLAYLIST_REQUEST_FAILURE';

// add to playlist
export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_REQUEST_SUCCESS = 'CREATE_PLAYLIST_REQUEST_SUCCESS';
export const CREATE_PLAYLIST_REQUEST_FAILURE = 'CREATE_PLAYLIST_REQUEST_FAILURE';


//user playlists 
export const USER_PLAYLISTS_FETCH_REQUEST = 'USER_PLAYLISTS_FETCH_REQUEST';
export const USER_PLAYLISTS_FETCH_REQUEST_SUCCESS = 'USER_PLAYLISTS_FETCH_REQUEST_SUCCESS';
export const USER_PLAYLISTS_FETCH_REQUEST_FAILURE = 'USER_PLAYLISTS_FETCH_REQUEST_FAILURE';
export const USER_PLAYLISTS_CLEAN_REQUEST = 'USER_PLAYLISTS_CLEAN_REQUEST';


// individual artist
export const INDIVIDUAL_ARTIST_FETCH_REQUEST = 'INDIVIDUAL_ARTIST_FETCH_REQUEST';
export const INDIVIDUAL_ARTIST_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_ARTIST_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_ARTIST_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_ARTIST_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_ARTIST_FETCH_MORE_REQUEST = 'INDIVIDUAL_ARTIST_FETCH_MORE_REQUEST';
export const INDIVIDUAL_ARTIST_FETCH_MORE_REQUEST_SUCCESS = 'INDIVIDUAL_ARTIST_FETCH_MORE_REQUEST_SUCCESS';
export const INDIVIDUAL_ARTIST_FETCH_MORE_REQUEST_FAILURE = 'INDIVIDUAL_ARTIST_FETCH_MORE_REQUEST_FAILURE';
export const INDIVIDUAL_ARTIST_FETCH_META_INFO = 'INDIVIDUAL_ARTIST_FETCH_META_INFO';
export const INDIVIDUAL_ARTIST_CLEAN_REQUEST = 'INDIVIDUAL_ARTIST_CLEAN_REQUEST';

export const ARTIST_SINGLE_SONG_FETCH_REQUEST = 'ARTIST_SINGLE_SONG_FETCH_REQUEST';
export const ARTIST_SINGLE_SONG_FETCH_SUCCESS = 'ARTIST_SINGLE_SONG_FETCH_SUCCESS';
export const ARTIST_SINGLE_SONG_FETCH_FAIL = "ARTIST_SINGLE_SONG_FETCH_FAIL"

// popularSongsByArtist
export const POPULAR_SONGS_BY_ARTIST_FETCH_REQUEST = 'POPULAR_SONGS_BY_ARTIST_FETCH_REQUEST';
export const POPULAR_SONGS_BY_ARTIST_FETCH_REQUEST_SUCCESS = 'POPULAR_SONGS_BY_ARTIST_FETCH_REQUEST_SUCCESS';
export const POPULAR_SONGS_BY_ARTIST_FETCH_REQUEST_FAILURE = 'POPULAR_SONGS_BY_ARTIST_FETCH_REQUEST_FAILURE';
export const POPULAR_SONGS_BY_ARTIST_CLEAN_REQUEST = 'POPULAR_SONGS_BY_ARTIST_CLEAN_REQUEST';

// related artists by Artist
export const RELATED_ARTISTS_BY_ARTIST_FETCH_REQUEST = 'RELATED_ARTISTS_BY_ARTIST_FETCH_REQUEST';
export const RELATED_ARTISTS_BY_ARTIST_FETCH_REQUEST_SUCCESS = 'RELATED_ARTISTS_BY_ARTIST_FETCH_REQUEST_SUCCESS';
export const RELATED_ARTISTS_BY_ARTIST_FETCH_REQUEST_FAILURE = 'RELATED_ARTISTS_BY_ARTIST_FETCH_REQUEST_FAILURE';
export const RELATED_ARTISTS_BY_ARTIST_CLEAN_REQUEST = 'RELATED_ARTISTS_BY_ARTIST_CLEAN_REQUEST';

// artist latest releases
export const ARTIST_LATEST_RELEASES_FETCH_REQUEST = 'ARTIST_LATEST_RELEASES_FETCH_REQUEST';
export const ARTIST_LATEST_RELEASES_FETCH_REQUEST_SUCCESS = 'ARTIST_LATEST_RELEASES_FETCH_REQUEST_SUCCESS';
export const ARTIST_LATEST_RELEASES_FETCH_REQUEST_FAILURE = 'ARTIST_LATEST_RELEASES_FETCH_REQUEST_FAILURE';
export const ARTIST_LATEST_RELEASES_FETCH_MORE_REQUEST = 'ARTIST_LATEST_RELEASES_FETCH_MORE_REQUEST';
export const ARTIST_LATEST_RELEASES_FETCH_MORE_REQUEST_SUCCESS = 'ARTIST_LATEST_RELEASES_FETCH_MORE_REQUEST_SUCCESS';
export const ARTIST_LATEST_RELEASES_FETCH_MORE_REQUEST_FAILURE = 'ARTIST_LATEST_RELEASES_FETCH_MORE_REQUEST_FAILURE';
export const ARTIST_LATEST_RELEASES_FETCH_META = 'ARTIST_LATEST_RELEASES_FETCH_META';
export const ARTIST_LATEST_RELEASES_CLEAN_REQUEST = 'ARTIST_LATEST_RELEASES_CLEAN_REQUEST';

// artist latest released album
export const ARTIST_LATEST_RELEASED_ALBUM_FETCH_REQUEST = 'ARTIST_LATEST_RELEASED_ALBUM_FETCH_REQUEST';
export const ARTIST_LATEST_RELEASED_ALBUM_FETCH_REQUEST_SUCCESS = 'ARTIST_LATEST_RELEASED_ALBUM_FETCH_REQUEST_SUCCESS';
export const ARTIST_LATEST_RELEASED_ALBUM_FETCH_REQUEST_FAILURE = 'ARTIST_LATEST_RELEASED_ALBUM_FETCH_REQUEST_FAILURE';
export const ARTIST_LATEST_RELEASED_ALBUM_CLEAN_REQUEST = 'ARTIST_LATEST_RELEASES_CLEAN_REQUEST';


// individual album
export const INDIVIDUAL_ALBUM_FETCH_REQUEST = 'INDIVIDUAL_ALBUM_FETCH_REQUEST';
export const INDIVIDUAL_ALBUM_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_ALBUM_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_ALBUM_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_ALBUM_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_ALBUM_CLEAN_REQUEST = 'INDIVIDUAL_ALBUM_CLEAN_REQUEST';

// individual album
export const FAVORITE_REQUEST = 'FAVORITE_REQUEST';
export const FAVORITE_REQUEST_SUCCESS = 'FAVORITE_REQUEST_SUCCESS';
export const FAVORITE_REQUEST_FAILURE = 'FAVORITE_REQUEST_FAILURE';
export const FAVORITE_CLEAN_REQUEST = 'INDIVIDUAL_ALBUM_CLEAN_REQUEST';


// related artists by album
export const RELATED_ARTISTS_BY_ALBUM_FETCH_REQUEST = 'RELATED_ARTISTS_BY_ALBUM_FETCH_REQUEST';
export const RELATED_ARTISTS_BY_ALBUM_FETCH_REQUEST_SUCCESS = 'RELATED_ARTISTS_BY_ALBUM_FETCH_REQUEST_SUCCESS';
export const RELATED_ARTISTS_BY_ALBUM_FETCH_REQUEST_FAILURE = 'RELATED_ARTISTS_BY_ALBUM_FETCH_REQUEST_FAILURE';
export const RELATED_ARTISTS_BY_ALBUM_CLEAN_REQUEST = 'RELATED_ARTISTS_BY_ALBUM_CLEAN_REQUEST';

// related albums by album
export const RELATED_ALBUMS_BY_ALBUM_FETCH_REQUEST = 'RELATED_ALBUMS_BY_ALBUM_FETCH_REQUEST';
export const RELATED_ALBUMS_BY_ALBUM_FETCH_REQUEST_SUCCESS = 'RELATED_ALBUMS_BY_ALBUM_FETCH_REQUEST_SUCCESS';
export const RELATED_ALBUMS_BY_ALBUM_FETCH_REQUEST_FAILURE = 'RELATED_ALBUMS_BY_ALBUM_FETCH_REQUEST_FAILURE';
export const RELATED_ALBUMS_BY_ALBUM_CLEAN_REQUEST = 'RELATED_ALBUMS_BY_ALBUM_CLEAN_REQUEST';


// individual playlist
export const INDIVIDUAL_PLAYLIST_FETCH_REQUEST = 'INDIVIDUAL_PLAYLIST_FETCH_REQUEST';
export const INDIVIDUAL_PLAYLIST_FETCH_REQUEST_SUCCESS = 'INDIVIDUAL_PLAYLIST_FETCH_REQUEST_SUCCESS';
export const INDIVIDUAL_PLAYLIST_FETCH_REQUEST_FAILURE = 'INDIVIDUAL_PLAYLIST_FETCH_REQUEST_FAILURE';
export const INDIVIDUAL_PLAYLIST_CLEAN_REQUEST = 'INDIVIDUAL_PLAYLIST_CLEAN_REQUEST';

// similar playlists by playlist
export const SIMILAR_PLAYLISTS_BY_PLAYLIST_FETCH_REQUEST = 'SIMILAR_PLAYLISTS_BY_PLAYLIST_FETCH_REQUEST';
export const SIMILAR_PLAYLISTS_BY_PLAYLIST_FETCH_REQUEST_SUCCESS = 'SIMILAR_PLAYLISTS_BY_PLAYLIST_FETCH_REQUEST_SUCCESS';
export const SIMILAR_PLAYLISTS_BY_PLAYLIST_FETCH_REQUEST_FAILURE = 'SIMILAR_PLAYLISTS_BY_PLAYLIST_FETCH_REQUEST_FAILURE';
export const SIMILAR_PLAYLISTS_BY_PLAYLIST_CLEAN_REQUEST = 'SIMILAR_PLAYLISTS_BY_PLAYLIST_CLEAN_REQUEST';

// related artists by playlist
export const RELATED_ARTISTS_BY_PLAYLIST_FETCH_REQUEST = 'RELATED_ARTISTS_BY_PLAYLIST_FETCH_REQUEST';
export const RELATED_ARTISTS_BY_PLAYLIST_FETCH_REQUEST_SUCCESS = 'RELATED_ARTISTS_BY_PLAYLIST_FETCH_REQUEST_SUCCESS';
export const RELATED_ARTISTS_BY_PLAYLIST_FETCH_REQUEST_FAILURE = 'RELATED_ARTISTS_BY_PLAYLIST_FETCH_REQUEST_FAILURE';
export const RELATED_ARTISTS_BY_PLAYLIST_CLEAN_REQUEST = 'RELATED_ARTISTS_BY_PLAYLIST_CLEAN_REQUEST';

// featured playlist
export const FEATURED_PLAYLIST_FETCH_REQUEST = 'FEATURED_PLAYLIST_FETCH_REQUEST';
export const FEATURED_PLAYLIST_FETCH_REQUEST_SUCCESS = 'FEATURED_PLAYLIST_FETCH_REQUEST_SUCCESS';
export const FEATURED_PLAYLIST_FETCH_REQUEST_FAILURE = 'FEATURED_PLAYLIST_FETCH_REQUEST_FAILURE';
export const FEATURED_PLAYLIST_CLEAN_REQUEST = 'FEATURED_PLAYLIST_CLEAN_REQUEST';


// advertisements
export const ADVERTISEMENT_FETCH_REQUEST = 'ADVERTISEMENT_FETCH_REQUEST';
export const ADVERTISEMENT_FETCH_REQUEST_SUCCESS = 'ADVERTISEMENT_FETCH_REQUEST_SUCCESS';
export const ADVERTISEMENT_FETCH_REQUEST_FAILURE = 'ADVERTISEMENT_FETCH_REQUEST_FAILURE';
export const ADVERTISEMENT_CLEAN_REQUEST = 'ADVERTISEMENT_CLEAN_REQUEST';
export const ADVERTISEMENT_BY_LOCATION_FETCH = 'ADVERTISEMENT_BY_LOCATION_FETCH';

// notification
export const NOTIFICATION_FETCH_REQUEST = 'NOTIFICATION_FETCH_REQUEST';
export const NOTIFICATION_FETCH_REQUEST_SUCCESS = 'NOTIFICATION_FETCH_REQUEST_SUCCESS';
export const NOTIFICATION_FETCH_REQUEST_FAILURE = 'NOTIFICATION_FETCH_REQUEST_FAILURE';
export const NOTIFICATION_CLEAN_REQUEST = 'NOTIFICATION_CLEAN_REQUEST';

// analytics
export const ANALYTICS_FETCH_REQUEST = 'ANALYTICS_FETCH_REQUEST';
export const ANALYTICS_FETCH_REQUEST_SUCCESS = 'ANALYTICS_FETCH_REQUEST_SUCCESS';
export const ANALYTICS_FETCH_REQUEST_FAILURE = 'ANALYTICS_FETCH_REQUEST_FAILURE';

//Add SONG TO CURRENT AUDIO QUEUE
export const ADD_SONG_TO_CURRENT_AUDIO_QUEUE = 'ADD_SONG_TO_CURRENT_AUDIO_QUEUE';
export const ADD_SONG_TO_CURRENT_AUDIO_QUEUE_CLEAN_REQUEST = 'ADD_SONG_TO_CURRENT_AUDIO_QUEUE_CLEAN_REQUEST';


//LANGUAGE
export const LANGUAGE_FETCH_REQUEST = 'LANGUAGE_FETCH_REQUEST';
export const LANGUAGE_FETCH_SUCCESS = 'LANGUAGE_FETCH_SUCCESS';
export const LANGUAGE_FETCH_FAIL = 'LANGUAGE_FETCH_FAIL';



/**
 * ARTIST DASHBOARD ACTION TYPES
 */

//Tags
export const TAG_FETCH_REQUEST = 'TAG_FETCH_REQUEST';
export const TAG_FETCH_SUCCESS = 'TAG_FETCH_SUCCESS';
export const TAG_FETCH_FAIL = 'TAG_FETCH_FAIL';

//ARTIST ANALYTICS COUNT
export const ARTIST_ANALYTICS_COUNTS_REQUEST = 'ARTIST_ANALYTICS_COUNTS_REQUEST';
export const ARTIST_ANALYTICS_COUNTS_SUCCESS = 'ARTIST_ANALYTICS_COUNTS_SUCCESS';
export const ARTIST_ANALYTICS_COUNTS_FAIL = 'ARTIST_ANALYTICS_COUNTS_FAIL';

// ARTIST TOTAL EARNINGS
export const ARTIST_TOTAL_EARNINGS_REQUEST = 'ARTIST_TOTAL_EARNINGS_REQUEST';
export const ARTIST_TOTAL_EARNINGS_SUCCESS = 'ARTIST_TOTAL_EARNINGS_SUCCESS';
export const ARTIST_TOTAL_EARNINGS_FAIL = 'ARTIST_TOTAL_EARNINGS_FAIL';

// ARTIST TOTAL FOLLOWERS
export const ARTIST_TOTAL_FOLLOWERS_REQUEST = 'ARTIST_TOTAL_FOLLOWERS_REQUEST';
export const ARTIST_TOTAL_FOLLOWERS_SUCCESS = 'ARTIST_TOTAL_FOLLOWERS_SUCCESS';
export const ARTIST_TOTAL_FOLLOWERS_FAIL = 'ARTIST_TOTAL_FOLLOWERS_FAIL';

// ARTIST TOTAL PLAY COUNTS
export const ARTIST_TOTAL_PLAY_COUNTS_REQUEST = 'ARTIST_TOTAL_PLAY_COUNTS_REQUEST';
export const ARTIST_TOTAL_PLAY_COUNTS_SUCCESS = 'ARTIST_TOTAL_PLAY_COUNTS_SUCCESS';
export const ARTIST_TOTAL_PLAY_COUNTS_FAIL = 'ARTIST_TOTAL_PLAY_COUNTS_FAIL';

// ARTIST SINGLE SONG PLAY COUNT
export const ARTIST_TOTAL_SINGLE_SONG_PLAY_COUNT_REQUEST = 'ARTIST_TOTAL_SINGLE_SONG_PLAY_COUNT_REQUEST';
export const ARTIST_TOTAL_SINGLE_SONG_PLAY_COUNT_SUCCESS = 'ARTIST_TOTAL_SINGLE_SONG_PLAY_COUNT_SUCCESS';
export const ARTIST_TOTAL_SINGLE_SONG_PLAY_COUNT_FAIL = 'ARTIST_TOTAL_SINGLE_SONG_PLAY_COUNT_FAIL';

// ARTIST SINGLE SONG EARNING
export const ARTIST_TOTAL_SINGLE_SONG_EARNING_REQUEST = 'ARTIST_TOTAL_SINGLE_SONG_EARNING_REQUEST';
export const ARTIST_TOTAL_SINGLE_SONG_EARNING_SUCCESS = 'ARTIST_TOTAL_SINGLE_SONG_EARNING_SUCCESS';
export const ARTIST_TOTAL_SINGLE_SONG_EARNING_FAIL = 'ARTIST_TOTAL_SINGLE_SONG_EARNING_FAIL';


// upload albums 
export const ARTIST_ALBUM_CREATE_REQUEST = "ARTIST_ALBUM_CREATE_REQUEST"
export const ARTIST_ALBUM_CREATE_SUCCESS = "ARTIST_ALBUM_CREATE_SUCCESS"
export const ARTIST_ALBUM_CREATE_FAIL = "ARTIST_ALBUM_CREATE_FAIL"
export const SET_CURRENT_EDIT_ALBUM = "SET_CURRENT_EDIT_ALBUM"
export const REMOVE_CURRENT_EDIT_ALBUM = "REMOVE_CURRENT_EDIT_ALBUM"

// my albums 
export const MY_ALBUMS_FETCH_REQUEST = "MY_ALBUMS_FETCH_REQUEST"
export const MY_ALBUMS_FETCH_SUCCESS = "MY_ALBUMS_FETCH_SUCCESS"
export const MY_ALBUMS_FETCH_FAIL = "MY_ALBUMS_FETCH_FAIL"
export const MY_ALBUM_LM_REQUEST = "MY_ALBUM_LM_REQUEST"
export const MY_ALBUM_LM_SUCCESS = "MY_ALBUM_LM_SUCCESS"
export const MY_ALBUM_LM_FAIL = "MY_ALBUM_LM_FAIL"


// my songs
export const MY_SONGS_FETCH_REQUEST = "MY_SONGS_FETCH_REQUEST"
export const MY_SONGS_FETCH_SUCCESS = "MY_SONGS_FETCH_SUCCESS"
export const MY_SONGS_META_FETCH_SUCCESS = "MY_SONGS_META_FETCH_SUCCESS"
export const MY_SONGS_FETCH_FAIL = "MY_SONGS_FETCH_FAIL"
export const MY_SONGS_LM_REQUEST = "MY_SONGS_LM_REQUEST"
export const MY_SONGS_LM_SUCCESS = "MY_SONGS_LM_SUCCESS"
export const MY_SONGS_LM_FAIL = "MY_SONGS_LM_FAIL"


// upload song 
export const UPLOAD_SONG_REQUEST = 'UPLOAD_SONG_REQUEST'
export const UPLOAD_SONG_SUCCESS = 'UPLOAD_SONG_SUCCESS'
export const UPLOAD_SONG_FAIL = 'UPLOAD_SONG_FAIL'
export const SET_CURRENT_EDIT_SONG = "SET_CURRENT_EDIT_SONG"
export const REMOVE_CURRENT_EDIT_SONG = "REMOVE_CURRENT_EDIT_SONG"


//artist banking details
export const BANK_DETAIL_FETCH_REQUEST = 'BANK_DETAIL_FETCH_REQUEST'
export const BANK_DETAIL_FETCH_SUCCESS = 'BANK_DETAIL_FETCH_SUCCESS'
export const BANK_DETAIL_FETCH_FAIL = 'BANK_DETAIL_FETCH_FAIL'


export const BANK_DETAIL_UPDATE_REQUEST = "BANK_DETAIL_UPDATE_REQUEST"
export const BANK_DETAIL_UPDATE_SUCCESS = "BANK_DETAIL_UPDATE_SUCCESS"
export const BANK_DETAIL_UPDATE_FAIL = "BANK_DETAIL_UPDATE_FAIL"



export const ARTIST_POPULAR_SONGS_REQUEST =  "ARTIST_POPULAR_SONGS_REQUEST"
export const ARTIST_POPULAR_SONGS_SUCCESS =  "ARTIST_POPULAR_SONGS_SUCCESS"
export const ARTIST_POPULAR_SONGS_FAIL =  "ARTIST_POPULAR_SONGS_FAIL"



export const FORGOT_PASSWORD_SUCCESS =  "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL =  "FORGOT_PASSWORD_FAIL";